version: '3'
 
services:
  merlin_unchained:
    image: johncapobianco/merlin_unchained
    build: 
      context: ./
      dockerfile: ./docker/dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "db"
  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=merlin
      - POSTGRES_PASSWORD=merlin
      - POSTGRES_DB=merlin
    volumes:
      - ./data/db:/var/lib/postgresql/data      